ntrees_min_meth: 2000
ntrees_min_dir: 2000
ntrees_min_file_ext: 1000
ntrees_min_long: 1000
ntrees_foreach_ip_url: 1000

sample_size_min_meth: 1000
sample_size_min_dir: 10000
sample_size_min_file_ext: 1000
sample_size_min_long: 1000
sample_size_foreach_ip_url: 1100

mesh_min_meth: 1500
mesh_min_dir: 2100
mesh_min_file_ext: 2000
mesh_min_long: 4000
mesh_foreach_ip_url: 2000

value_min_meth: 0.25
value_min_dir: 0.25
value_min_file_ext: 0.25
value_min_long: 0.25
value_foreach_ip_url: 0.25

dangerous_value_extra: 0.2